### PR TITLE
Update editors

### PR DESCRIPTION
**Pull request by domenic**
Scott has agreed to take over maintenance of this spec from myself and Shubhie. Hooray!

***
<a href="https://pr-preview.s3.amazonaws.com/WICG/page-lifecycle/pull/44.html" title="Last updated on Jun 9, 2022, 5:20 PM UTC (1194719)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/page-lifecycle/44/d227df9...1194719.html" title="Last updated on Jun 9, 2022, 5:20 PM UTC (1194719)">Diff</a>

### CODE REVIEW

**Comment by domenic** [comment]
Closing and reopening to try to fix the IPR checker.

**Comment by shaseley** [comment]
> Closing and reopening to try to fix the IPR checker.

It worked! What happened, broken hook?

**Review by shaseley — APPROVED** [review]
lgtm!

**Comment by domenic** [comment]
Yeah, apparently there's an epidemic of two IPR webhooks going around WICG. One broken, one working. Once I deleted the broken one and re-triggered the check by closing and reopening, everything worked.

**Pull request merged**
